// PUBLIC testnet contract IDs. Generated by scripts/deploy-contracts.sh; do not edit by hand.
export const RPC_URL = "https://soroban-testnet.stellar.org";
export const NETWORK_PASSPHRASE = "Test SDF Network ; September 2015";

/** Ledger at deploy time: contract events are read from here on. */
export const START_LEDGER = 4862600;

export const USDC = {
  code: "USDC",
  issuer: "GD7VYUJX7JUXC2TPCUYYYBEQ7MKPCE2OTPHPF3C4YXXAMQMHSIH3GQMD",
  contract: "CCPIEEIELQ3VJSQFFIE6W2VZD3EDTUR47FYYCQCGQPKLEHTY4OHJJ2HF",
  decimals: 7,
} as const;

export const CONTRACTS = {
  shop: "CC2HF7CDBREISPCSXF77HSQXE7JJT7WBWFZQZU75CRW37FYBLB65YXOG",
  airline: "CCIT25V7NOVVBCVWPSE6ULFRNM3ISQRMEMF7C4PRE73DG3IFFPIXSAA3",
  museum: "CDRNZBM5FUGXSMV5SFVNCXG3D6CZWERELD4S7DU6PGOMRTV22VNJOKNB",
  wallet: "CDGONC6MHGC3EONC4DLBRKAFDTBD6KWCGBMASAM3AZNFH6C32WME3AAW",
  spendingPolicy: "CCZWAFMQ4MSIMDKWOAGDL3UAUMIGTZSGDFTNAXX7FY2ASQKZ4HOGLV4W",
  verifier: "CDAK7LZZ2V2O2YUHRZWBQUWZJEWSLX636XG2WSHTHMQOAOUMGQNFZNYD",
} as const;

/** Smart wallet context rule IDs (see contracts/smart-wallet). */
export const WALLET_RULES = {
  owner: 0,
  usdc: 1,
  shop: 2,
  airline: 3,
  museum: 4,
} as const;
