// PUBLIC testnet contract IDs. Generated by scripts/deploy-contracts.sh; do not edit by hand.
export const RPC_URL = "https://soroban-testnet.stellar.org";
export const NETWORK_PASSPHRASE = "Test SDF Network ; September 2015";

/** Ledger at deploy time: contract events are read from here on. */
export const START_LEDGER = 4863523;

export const USDC = {
  code: "USDC",
  issuer: "GD7VYUJX7JUXC2TPCUYYYBEQ7MKPCE2OTPHPF3C4YXXAMQMHSIH3GQMD",
  contract: "CCPIEEIELQ3VJSQFFIE6W2VZD3EDTUR47FYYCQCGQPKLEHTY4OHJJ2HF",
  decimals: 7,
} as const;

export const CONTRACTS = {
  shop: "CBV2WQXFL44ZABLFIOKUE53SPHQI2YA5YZSGRSMIOMUK2VZMOEK2QMJQ",
  airline: "CAWSRJJX5DX6QABTMW5M3SY3PDID5AFVDBGATVOYSVKL5OTRQ22JHBZM",
  museum: "CCIFUIPW67J7H4FCIACBIESUK5WQOUD5IFHWGN5J345APBQRLF2CCXCY",
  wallet: "CD3VSMPMUEYU7T43XY4E7MQ3NCOO775WGSCVE2K3LRUI4XQJV3GAXPD5",
  spendingPolicy: "CDXGEHL7X4IXOXTUMAIQ425RA3VKLIOHGOVXSACVO2HEY56TZD3AXND7",
  verifier: "CBQRY6KJSIRJHY3WLBUWGDUVCWYNKEQOHRZN6WL7TJOR2IIENAXIGYQO",
} as const;

/** Smart wallet context rule IDs (see contracts/smart-wallet). */
export const WALLET_RULES = {
  owner: 0,
  usdc: 1,
  shop: 2,
  airline: 3,
  museum: 4,
} as const;
