// PUBLIC testnet contract IDs. Generated by scripts/deploy-contracts.sh; do not edit by hand.
export const RPC_URL = "https://soroban-testnet.stellar.org";
export const NETWORK_PASSPHRASE = "Test SDF Network ; September 2015";

/** Ledger at deploy time: contract events are read from here on. */
export const START_LEDGER = 4863955;

export const USDC = {
  code: "USDC",
  issuer: "GD7VYUJX7JUXC2TPCUYYYBEQ7MKPCE2OTPHPF3C4YXXAMQMHSIH3GQMD",
  contract: "CCPIEEIELQ3VJSQFFIE6W2VZD3EDTUR47FYYCQCGQPKLEHTY4OHJJ2HF",
  decimals: 7,
} as const;

export const CONTRACTS = {
  shop: "CACVPCDPWTIBLCHV5N4GURFPOUHW4Z4EOV5EEAR6REHCDJMBDPFTQGKZ",
  airline: "CARWLR7B66MPZZ6MCWBCYEJSD6MUVBKXUXAG77NRNLDM2NT25KH22IGE",
  museum: "CBPSXYZ4FZQZH24YQITRJ3VLZELE34EBDEH5R657CW7S3SWYLTSVKSUJ",
  wallet: "CDCWTWAL6KYGU6HFDMEN7ULSK5XORKSZBQAKKBPMCRZR36ERPMX7ZEGS",
  spendingPolicy: "CDRTVEJ5IPEPGLSXV4SEC5GRW4WLOW7WS4JAEZ4K3ZUZYZQHBOK5QG52",
  verifier: "CA22HFVN7BFXMMEG7QEZGAJENBNFUPO64BBZD7GRCDKK3EGMQFTMZFH7",
} as const;

/** Smart wallet context rule IDs (see contracts/smart-wallet). */
export const WALLET_RULES = {
  owner: 0,
  usdc: 1,
  shop: 2,
  airline: 3,
  museum: 4,
} as const;
