#!/usr/bin/env bash
# Regenerate + Friendbot-fund all Stellar TESTNET actor accounts, then
# redeploy the contracts (scripts/deploy-contracts.sh).
# - Secrets   -> .env.local (only STELLAR_*_SECRET lines are replaced/added)
# - Addresses -> config/actors.ts, contract IDs -> config/contracts.ts (public, committed)
#
# Usage:  ./scripts/reset-testnet.sh [--keys-only] [--vercel]
#   --keys-only  only regenerate accounts, skip contract deployment
#   --vercel     also upload the new STELLAR_* secrets to Vercel
set -euo pipefail

cd "$(dirname "$0")/.."

KEYS_ONLY=0
VERCEL=0
for arg in "$@"; do
  case "$arg" in
    --keys-only) KEYS_ONLY=1 ;;
    --vercel) VERCEL=1 ;;
    *) echo "unknown option: $arg"; exit 1 ;;
  esac
done

NETWORK="testnet" # TESTNET ONLY. Never change this to mainnet.
CONFIG_DIR=".stellar-cli" # project-local Stellar CLI config (git-ignored)
ENV_FILE=".env.local"

# actor-name:ENV_PREFIX
ACTORS=(
  "user:USER"
  "government:GOV"
  "recycler:RECYCLER"
  "shop:SHOP"
  "airline:AIRLINE"
  "museum:MUSEUM"
  "oracle:ORACLE"
  "issuer:ISSUER" # issues the demo USDC
  "agent:AGENT"   # Dino's signing key for the user's smart wallet (spending-limited)
)

command -v stellar >/dev/null || { echo "stellar CLI not found"; exit 1; }
[ -f "$ENV_FILE" ] || { echo "$ENV_FILE not found"; exit 1; }

cp "$ENV_FILE" "$ENV_FILE.bak"

# Replace KEY=... in .env.local, or append it if missing. Other lines untouched.
set_env() {
  local key="$1" value="$2" tmp
  tmp="$(mktemp)"
  if grep -q "^${key}=" "$ENV_FILE"; then
    awk -v k="$key" -v v="$value" 'index($0, k"=")==1 { print k"="v; next } { print }' "$ENV_FILE" > "$tmp"
  else
    cat "$ENV_FILE" > "$tmp"
    [ -z "$(tail -c1 "$tmp")" ] || echo >> "$tmp"
    echo "${key}=${value}" >> "$tmp"
  fi
  cat "$tmp" > "$ENV_FILE"
  rm -f "$tmp"
}

grep -q "^# Stellar testnet" "$ENV_FILE" || printf '\n# Stellar testnet (managed by scripts/reset-testnet.sh)\n' >> "$ENV_FILE"

ts_entries=""
for entry in "${ACTORS[@]}"; do
  name="${entry%%:*}"
  prefix="${entry##*:}"
  echo "-> $name: generating + funding via Friendbot"
  stellar --config-dir "$CONFIG_DIR" keys generate "$name" \
    --network "$NETWORK" --as-secret --fund --overwrite -q
  secret="$(stellar --config-dir "$CONFIG_DIR" keys secret "$name")"
  address="$(stellar --config-dir "$CONFIG_DIR" keys address "$name")"
  set_env "STELLAR_${prefix}_SECRET" "$secret"
  echo "   $address"
  ts_entries+="  ${name}: \"${address}\",\n"
done

mkdir -p config
cat > config/actors.ts <<EOF
// PUBLIC testnet addresses. Generated by scripts/reset-testnet.sh; do not edit by hand.
// Secrets live in .env.local as STELLAR_<ACTOR>_SECRET.
export const STELLAR_NETWORK = "testnet" as const;
export const HORIZON_URL = "https://horizon-testnet.stellar.org";
export const EXPLORER_URL = "https://stellar.expert/explorer/testnet";

export const ACTORS = {
$(printf "%b" "$ts_entries")} as const;

export type ActorName = keyof typeof ACTORS;
EOF

echo "Accounts done. Updated $ENV_FILE (backup: $ENV_FILE.bak) and config/actors.ts"

if [ "$KEYS_ONLY" = 0 ]; then
  ./scripts/deploy-contracts.sh
fi

if [ "$VERCEL" = 1 ]; then
  node scripts/push-env-to-vercel.mjs STELLAR_
fi
