#!/usr/bin/env bash
# Regenerate + Friendbot-fund all Stellar TESTNET actor accounts.
# - Secrets  -> .env.local (only STELLAR_*_SECRET lines are replaced/added)
# - Addresses -> config/actors.ts (public, committed)
# Run after a testnet reset:  ./scripts/reset-testnet.sh
# Then re-upload env vars to Vercel (see README).
set -euo pipefail

cd "$(dirname "$0")/.."

NETWORK="testnet" # TESTNET ONLY. Never change this to mainnet.
CONFIG_DIR=".stellar-cli" # project-local Stellar CLI config (git-ignored)
ENV_FILE=".env.local"

# actor-name:ENV_PREFIX
ACTORS=(
  "user:USER"
  "government:GOV"
  "recycler:RECYCLER"
  "shop:SHOP"
  "airline:AIRLINE"
  "museum:MUSEUM"
  "oracle:ORACLE"
)

command -v stellar >/dev/null || { echo "stellar CLI not found"; exit 1; }
[ -f "$ENV_FILE" ] || { echo "$ENV_FILE not found"; exit 1; }

cp "$ENV_FILE" "$ENV_FILE.bak"

# Replace KEY=... in .env.local, or append it if missing. Other lines untouched.
set_env() {
  local key="$1" value="$2" tmp
  tmp="$(mktemp)"
  if grep -q "^${key}=" "$ENV_FILE"; then
    awk -v k="$key" -v v="$value" 'index($0, k"=")==1 { print k"="v; next } { print }' "$ENV_FILE" > "$tmp"
  else
    cat "$ENV_FILE" > "$tmp"
    [ -z "$(tail -c1 "$tmp")" ] || echo >> "$tmp"
    echo "${key}=${value}" >> "$tmp"
  fi
  cat "$tmp" > "$ENV_FILE"
  rm -f "$tmp"
}

grep -q "^# Stellar testnet" "$ENV_FILE" || printf '\n# Stellar testnet (managed by scripts/reset-testnet.sh)\n' >> "$ENV_FILE"

ts_entries=""
for entry in "${ACTORS[@]}"; do
  name="${entry%%:*}"
  prefix="${entry##*:}"
  echo "-> $name: generating + funding via Friendbot"
  stellar --config-dir "$CONFIG_DIR" keys generate "$name" \
    --network "$NETWORK" --as-secret --fund --overwrite -q
  secret="$(stellar --config-dir "$CONFIG_DIR" keys secret "$name")"
  address="$(stellar --config-dir "$CONFIG_DIR" keys address "$name")"
  set_env "STELLAR_${prefix}_SECRET" "$secret"
  echo "   $address"
  ts_entries+="  ${name}: \"${address}\",\n"
done

mkdir -p config
cat > config/actors.ts <<EOF
// PUBLIC testnet addresses. Generated by scripts/reset-testnet.sh; do not edit by hand.
// Secrets live in .env.local as STELLAR_<ACTOR>_SECRET.
export const STELLAR_NETWORK = "testnet" as const;
export const HORIZON_URL = "https://horizon-testnet.stellar.org";
export const EXPLORER_URL = "https://stellar.expert/explorer/testnet";

export const ACTORS = {
$(printf "%b" "$ts_entries")} as const;

export type ActorName = keyof typeof ACTORS;
EOF

echo "Done. Updated $ENV_FILE (backup: $ENV_FILE.bak) and config/actors.ts"
